In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold

In [72]:
def linear_reg(x, y, l=0.1, times=1000):
    w = np.mat(np.zeros((4, 1)))
    m = len(x)
    J_old=0
    J_new=0
    for i in range(times):
        a=l*(1/m)*x.T*(x*w - y)
        w = w - a
        J_new=(1/(2*m))*(x*w-y).T*(x*w-y)
        if(np.abs(J_new-J_old)<0.0001):
            break
        J_old=J_new
    print(a)
    return w
    

In [73]:
def feature_scaling(x):
    x_norm=np.mat(x)
    mu=np.mean(x_norm,axis=0)
    std=np.std(x_norm,axis=0,ddof=1)#无偏
    print(mu,std)
    x_norm=(x_norm-mu)/std
    return x_norm.A

In [74]:
data = pd.read_csv('11_train.csv')
m=len(data)
x = np.array(data.iloc[:, 1:4])
y =np.array(data.iloc[:,4])
data = np.array(data)
#feature scaling
x=feature_scaling(x)
x=np.insert(x,0,values=np.ones(m),axis=1)
print(x,y)

[[146.09794368  23.25078835  30.29808736]] [[85.20668495 14.69084725 21.52130663]]
[[ 1.          0.62434336 -1.43324469 -0.40499278]
 [ 1.         -0.34182592 -1.08913695 -0.34781076]
 [ 1.          0.63062864  1.67444067  1.37536052]
 [ 1.          0.86460471  0.6525046   0.3369125 ]
 [ 1.         -0.42465679 -0.66680355  0.08981787]
 [ 1.         -1.21207864  0.13309959 -0.45215571]
 [ 1.         -0.66515505  0.076812    2.00501799]
 [ 1.         -0.0886128  -1.41361076 -0.20377585]
 [ 1.         -0.04366652  0.44925836 -0.84834915]
 [ 1.          0.95381954  0.91711484  0.07444752]
 [ 1.          1.00243179 -1.00654563 -0.98174337]
 [ 1.         -0.65664596 -1.56004232 -0.3707846 ]
 [ 1.         -0.09548194  1.52259839  1.2517455 ]
 [ 1.         -0.81679187 -0.77195272 -1.12900148]
 [ 1.         -1.08763883 -1.52608849 -0.40703017]
 [ 1.         -0.09147674 -0.6224199  -0.97743574]
 [ 1.         -0.71319587  0.75927673  0.90794723]
 [ 1.         -0.82920579 -0.17152369  0.09620235]

In [75]:

kf = KFold(10, shuffle=True, random_state=2)
sum1=0
sum2=0
for train_data, test_data in kf.split(data):
    x_train=np.mat(x[train_data])
    y_train=np.mat(y[train_data]).T
    x_test=np.mat(x[test_data])
    y_test=np.mat(y[test_data]).T
    #print(x_train)
    #print(y_train)
    w = linear_reg(x_train, y_train)
    print(w)
    a=x_test*w-y_test
    b=x_train*w-y_train
    J1=(a.T*a)/len(x_test)
    J2=(b.T*b)/len(x_train)
    sum1=sum1+J1
    sum2=sum2+J2
final_cost1=sum1/10.0
final_cost2=sum2/10.0
print('当sigma={0},训练误差为{1},测试误差为{2}'.format(0,final_cost2,final_cost1))

[[-0.00254628]
 [-0.0002384 ]
 [-0.00162156]
 [ 0.00112295]]
[[1.40369738e+01]
 [3.78704510e+00]
 [2.80613276e+00]
 [1.08620597e-02]]
[[-0.00201741]
 [-0.00053623]
 [-0.00147948]
 [ 0.00187891]]
[[14.15688857]
 [ 3.90703105]
 [ 2.78393244]
 [ 0.02356853]]
[[-0.00186128]
 [-0.00019423]
 [-0.0017004 ]
 [ 0.00174051]]
[[14.03937185]
 [ 3.89038757]
 [ 2.789724  ]
 [ 0.0373255 ]]
[[-0.00179573]
 [-0.00068057]
 [-0.00149922]
 [ 0.00188189]]
[[14.04649347]
 [ 3.8767421 ]
 [ 2.73381458]
 [ 0.09553535]]
[[-1.69730136e-03]
 [-6.28496377e-05]
 [-1.72516436e-03]
 [ 1.88682942e-03]]
[[14.12635061]
 [ 3.85401303]
 [ 2.79604835]
 [ 0.06140456]]
[[-0.00258409]
 [-0.00077313]
 [-0.00087325]
 [ 0.00131663]]
[[ 1.41818185e+01]
 [ 3.91110724e+00]
 [ 2.77094691e+00]
 [-2.65311539e-03]]
[[-0.00188932]
 [-0.00059218]
 [-0.00183905]
 [ 0.00170266]]
[[14.06516207]
 [ 3.76662376]
 [ 2.75963453]
 [ 0.07381467]]
[[-0.00204813]
 [-0.00027109]
 [-0.00145454]
 [ 0.00157827]]
[[14.11967182]
 [ 3.80455374]
 [ 2.777819